### ISSUE TITLE
Protected Function Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [leatrix/leatrix-maps#1]
I'm getting the following error with Leatrix_Maps-9.0.11.

1x [ADDON_ACTION_BLOCKED] AddOn 'Leatrix_Maps' tried to call the protected function 'WorldMapFrame:SetScale()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetScale'
[string "@Leatrix_Maps\Leatrix_Maps-9.0.11.lua"]:627: in function <Leatrix_Maps\Leatrix_Maps.lua:617>
[string "=[C]"]: in function `SynchronizeDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:141: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:85: in function `HandleUserActionOpenQuestLog'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:448: in function `OpenQuestLog'
[string "@Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua"]:208: in function <..._ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua:195>

**Comment by leatrix** [comment]
This error may appear every now and then, usually when you click a quest or quest item in the objective tracker during combat.  Reloading your UI (/reload) should resolve it.  Unfortunately, it's not possible to completely remove these errors but you can reduce the chances of them happening by (a) only enable options in Leatrix Maps that you specifically want to use, don't enable options that you won't use and (b) avoid clicking quests or quest items in the objective tracker, especially during combat.

**Comment by MetalHeadSeven** [comment]
Thanks for the info.
