### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-maps#10]
**Hello 😊**

Opening the map causes an FPS hiccup, like a 0,5 sec freeze after the recent update. There are no errors caught by Bugger or anything.

**Thanks!**

**Comment by leatrix** [comment]
Happens with the default UI too (with all addons including LTM disabled).
Disable all addons except LTM and open your map.  If you get a stutter, disable LTM and open your map again in exactly the same location.  Is the stutter still present?

**Comment by Natlyz** [comment]
Thanks for reply. Yeah, I've tested it and I still get a stutter with default UI 😱

**Comment by leatrix** [comment]
Best thing to do is report it to Blizzard using the in-game bug report tool in the support menu.  Opening the map without the quest log showing might help a bit for now.

**Comment by Natlyz** [comment]
Done. I've submitted a bug report!

Thanks 😉
