### ISSUE TITLE
World quest tracker

### ISSUE THREAD

**Issue by manbats** [leatrix/leatrix-maps#11]
when you run worrld quest tracker it causes the map to always open in the middle of the screen

**Comment by leatrix** [comment]
This happens with the default UI too.  It's nothing to do with LTM.

You can fix it though.

- Open the world map with World Quest Tracker enabled.
- Hover your pointer over the 'Options' button in the bottom-left corner of the map frame.
- In the menu that opens, uncheck 'Map Window Centralized'.
- Your UI will be reloaded.
- The world map will no longer open centered.
