### ISSUE TITLE
Can't put the map on the left top corner

### ISSUE THREAD

**Issue by Rubyurek** [leatrix/leatrix-maps#16]
i deactivate the border of the map but i can't put it on the corner.
![Map with border](https://user-images.githubusercontent.com/42946288/180492015-cd8b3247-9cfc-4827-b5ff-925c06c2a956.png)
![Map without border](https://user-images.githubusercontent.com/42946288/180492024-e9e04261-4e6f-42ed-8754-df4bf9d86837.png)

**Comment by leatrix** [comment]
Are you using an addon called Demodal?

If not, disable all other addons, verify it works then enable other addons gradually until you find the addon causing the problem then let me know what that addon is.

**Comment by Rubyurek** [comment]
Yes i use the Addon Demodal. The joke is last update i don't have these problems. I update it leatris maps and now i have this issues.

**Comment by leatrix** [comment]
The same issue existed before the last update.  That's how I knew about it.  It's caused by Demodal clamping the map to the screen so it's nothing to do with LTM.  Even so, I added a fix in the latest alpha releases for all games so let me know if you have any issues after installing it.

**Comment by Rubyurek** [comment]
I download the alpha and now it works :)

**Comment by leatrix** [comment]
Awesome.  Thanks for letting me know.
