### ISSUE TITLE
English map on localized client

### ISSUE THREAD

**Issue by haenschen** [leatrix/leatrix-maps#19]
Is it possible to show the english map instead of the localized map with this addon? This would make it possible to e.g. play dragonflight beta with a working map instead of just green placeholders.

**Comment by leatrix** [comment]
Map data is locale independent.  Do you have a screenshot?

**Comment by haenschen** [comment]
![image](https://user-images.githubusercontent.com/9266844/193431078-668c2238-0461-4bde-917f-f215fdb1a5ad.png)

**Comment by leatrix** [comment]
Thank you for the screenshot and link.  I checked the game files and the map files don't yet exist for non-enUS clients.  You will just need to do what the forum post says and change your locale to enUS and/or wait for Blizzard to fix it.
