### ISSUE TITLE
Error when reporting ads in group finder

### ISSUE THREAD

**Issue by raysmith59** [leatrix/leatrix-maps#22]
Sometimes errors, sometimes works, haven't found any sort of pattern.

I disabled all addons except Leatrix Maps (v9.2.41), I enabled the taint log and got the error below; the LUA error is further down.  Disabling LM I haven't experienced any issues.

Taintlog:
10/10 16:33:07.373  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by Leatrix_Maps - Interface\SharedXML\UIDropDownMenu.lua:37
10/10 16:33:07.373      securecall()
10/10 16:33:07.373      Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
10/10 16:33:07.373      Interface\FrameXML\EasyMenu.lua:21 EasyMenu()
10/10 16:33:07.373      Interface\FrameXML\LFGList.lua:2619
10/10 16:33:07.373  Execution tainted by Leatrix_Maps while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\SharedXML\UIDropDownMenu.lua:864 UIDropDownMenu_GetSelectedID()
10/10 16:33:07.373      Interface\SharedXML\UIDropDownMenu.lua:539 UIDropDownMenu_AddButton()
10/10 16:33:07.373      Interface\FrameXML\EasyMenu.lua:30 initFunction()
10/10 16:33:07.373      Interface\SharedXML\UIDropDownMenu.lua:78 UIDropDownMenu_Initialize()
10/10 16:33:07.373      Interface\SharedXML\UIDropDownMenu.lua:1075 ToggleDropDownMenu()
10/10 16:33:07.373      Interface\FrameXML\EasyMenu.lua:22 EasyMenu()
10/10 16:33:07.373      Interface\FrameXML\LFGList.lua:2619
10/10 16:33:07.373  Interface\SharedXML\UIDropDownMenu.lua:916 UIDropDownMenuButton_OnClick()
10/10 16:33:07.373  An action was blocked because of taint from Leatrix_Maps - SendReport()
10/10 16:33:07.373      Interface\FrameXML\ReportFrame.lua:171 ReportFrame:SendReport()
10/10 16:33:07.373      Interface\FrameXML\ReportFrame.lua:75 ReportFrame:InitiateReportInternal()
10/10 16:33:07.373      Interface\FrameXML\ReportFrame.lua:427
10/10 16:33:07.373      ReportFrame:SetAttribute()
10/10 16:33:07.373      Interface\FrameXML\ReportFrame.lua:52 ReportFrame:InitiateReport()
10/10 16:33:07.373      Interface\FrameXML\LFGList.lua:3281 LFGList_ReportAdvertisement()
10/10 16:33:07.373      Interface\FrameXML\LFGList.lua:3313 func()
10/10 16:33:07.373      Interface\SharedXML\UIDropDownMenu.lua:918 UIDropDownMenuButton_OnClick()
10/10 16:33:07.373      DropDownList1Button4:OnClick()

LUA error:
5x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'SendReport()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:171: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:75: in function `InitiateReportInternal'
[string "@FrameXML\ReportFrame.lua"]:427: in function <FrameXML\ReportFrame.lua:413>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\ReportFrame.lua"]:52: in function `InitiateReport'
[string "@FrameXML\LFGList.lua"]:3281: in function `LFGList_ReportAdvertisement'
[string "@FrameXML\LFGList.lua"]:3313: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:918: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-maps-wrath/issues/56
