### ISSUE TITLE
Suggestion - add a scale setting for icons

### ISSUE THREAD

**Issue by Daeveren** [leatrix/leatrix-maps#26]
As the title says, an option to separately scale the icons on the map (separate from the map scale itself) would be handy.
When playing at high scale (in my own example, it's at 170%), the icons that come from the default map are huge, such as the 2 yellow stars, the mushrooms and the treasure chests (click the image to see it at 100%). Addons that place objects on the map have a separarate, fixed icon size, which is independent of the LTM scaling.
I don't even know if this scaling can even be done, but here I am, hoping it can be done one day :)
![R4NL76hq0j](https://user-images.githubusercontent.com/6321337/198400144-e009c1ce-f386-45eb-ba6e-bc9f6ec9272b.jpg)

**Comment by Daeveren** [comment]
Mapster addon has the following scale options (EJ = encounter journal)
![image](https://user-images.githubusercontent.com/6321337/199909880-f95366c8-318e-46b7-b8d9-51049cc1f2da.png)

**Comment by leatrix** [comment]
Are you using an addon such as TomCatTours or another map addon?  The last time someone reported huge icons such as stars on the world map, it was caused by TomCatTours.

**Comment by Daeveren** [comment]
Not using TomCatTours and I've looked through the rare scanning addons I have for any scaling options but they seem to only adjust their own "boss/treasure" icons.
Here's the frame inspect result for that specific object if you can read anything from it. I'll try to disable addons and see what happens.

![image](https://user-images.githubusercontent.com/6321337/199941428-81ced393-9ff6-4836-ac54-c96038589503.png)

**Comment by Daeveren** [comment]
Default UI, no addons loaded:

![image](https://user-images.githubusercontent.com/6321337/199951044-26f53621-e359-4555-be25-483de1aca9f4.png)

zoomed in
![image](https://user-images.githubusercontent.com/6321337/199951090-affe3d32-146f-475a-88fb-db76144fbb4f.png)

**Comment by rodalpho** [comment]
Agree, this would be a great enhancement. The huge icons look weird.
