### ISSUE TITLE
2x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'UseAction()'.

### ISSUE THREAD

**Issue by MiLeX84** [leatrix/leatrix-maps#27]
2x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON7"]:2: in function <[string "ACTIONBUTTON7"]:1>

Installed Version: Leatrix_Maps-10.0.01.zip

**Comment by MiLeX84** [comment]
For context, this happened a few times over the last few days, happening right after entering a dungeon, e.g. Sethekk Halls (this time) or after queuing for the Headless Horsemen event.

**Comment by zeenk** [comment]
I'm getting the same lua error 
```1x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:22: in function `MultiActionButtonUp'
[string "MULTIACTIONBAR1BUTTON9"]:4: in function <[string "MULTIACTIONBAR1BUTTON9"]:1>```

Happened when I used this keybind macro
```#showtooltip Burning Rush
/use Prismatic Bauble
/cancelaura Burning Rush
/cast Burning Rush
```

**Comment by leatrix** [comment]
Couple of things to note:

This sort of error is more likely to occur if you use or have used any of the zoom settings during your current login session (remember zoom level, increase zoom level, center map on player and scale the map).  Do you use any of these options?

It's also more likely to occur if you click anything in the objective tracker especially during combat.

Reloading your UI will clear this error from memory temporarily.

**Comment by Nillx** [comment]
Disabling the map scale makes me sad, i used to love how its not on my whole screen. Was that actually causing errors? I didnt saw any while i was using it.

**Comment by Nillx** [comment]
Oh i understand.. hope Blizz fix it.

**Comment by leatrix** [comment]
The issue with needing to replace Blizzard's GetCursorPosition function for scaling to work is referenced here:
https://github.com/Stanzilla/WoWUIBugs/issues/338

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-maps/issues/40
