### ISSUE TITLE
Blocked macro

### ISSUE THREAD

**Issue by Neischa** [leatrix/leatrix-maps#28]
Since 10.0 update there is an error when pressing any macro button saying: "Leatrix maps. A stop error has occurred but no need to worry. It can happen from time to time. Click the reload button to resolve it. It happens about twice per hour.
![image](https://user-images.githubusercontent.com/103169596/199307876-ce710261-8d51-4c45-a2a5-c5d90172e597.png)

**Comment by leatrix** [comment]
In the latest LTM release, the zoom settings are currently unavailable.  It would be helpful if you would let me know if the macro problem is resolved for you after you update to this version.  It's still always best not to click anything in the objective tracker though, especially during combat.

**Comment by Neischa** [comment]
Hi, thanks for answer and assigning the issue to the right place, sorry for that!
This is settings I have right now:
![image](https://user-images.githubusercontent.com/103169596/199568857-2a186bd7-984c-48ee-b1d0-589ea85f829f.png)

I think I had increased zoom level enabled before, so maybe that caused the issue. I will let you know if it happens again. Is there anything else I can do for you? Some log or something which helps you find the root cause (if it happens again...)?
Btw. thanks for great addons!

**Comment by leatrix** [comment]
The best way you can help is just to let me know if it happens again or how often it happens now.

There's still a rare chance that you will see that same reload window and the chances of seeing it increases if you click anything in the objective tracker, especially during combat.  It's not possible to remove that chance completely but it should happen a lot less than before.

**Comment by Neischa** [comment]
It seems it is fixed now as I got error with Venture Plan instead - same error, only blizz error message instead of addon specific error message - when clicking on macro it is ok, when pressing it via hotkey it displays that error message.
![image](https://user-images.githubusercontent.com/103169596/199577202-aac023da-46ca-4525-b1ed-1378e3ffb09f.png)

So you can close the issue and I will continue on Venture plan page probably:D
Thanks!!!
