### ISSUE TITLE
Permanently display icons on the large map 

### ISSUE THREAD

**Issue by Rubyurek** [leatrix/leatrix-maps#29]
Would there be a possibility to add a function for Leatrix Maps to permanently display icons on the large map (a la Handynotes only slimmed down)?

For example: Show icons of mailbox, auction house etc.

**Comment by leatrix** [comment]
Suggestions appreciated.  Some icons are shown for LTM for Wrath Classic and Classic Era but it's unlikely they will be added for LTM for Dragonflight.
