### ISSUE TITLE
Small map not registered as closed if closed through closeBox

### ISSUE THREAD

**Issue by StingrayNine** [leatrix/leatrix-maps#3]
https://user-images.githubusercontent.com/1285293/103832918-d9330400-507f-11eb-9276-d541e3c4f243.mp4
Not the biggest issue, but annoying when you forget

**Comment by leatrix** [comment]
Thanks for the report.  Should be fixed in the latest alpha (at least 9.0.12.alpha.1).
https://www.curseforge.com/wow/addons/leatrix-maps/files/all
