### ISSUE TITLE
Unable to zoom the quest map

### ISSUE THREAD

**Issue by ned406** [leatrix/leatrix-maps#32]
Hi, I used LTM for its ability to scale the "quest map" as I find the world map too large but that feature is gone.

Is it possible to add back? I know it can taint the game however Mapster has added the ability to scale the frame and it seems to work most of the time. The zoom was why I fell in love with the addon

**Comment by leatrix** [comment]
Blizzard have never supported map scaling but it was included with LTM until Dragonflight.  In Dragonflight, Blizzard's code changes made it impossible to continue to support map scaling without causing issues.  As far as I'm aware, Mapster locked out the scaling option for the same reason then added it back after complaints even though the author acknowledges that map scaling in Dragonblight causes UI issues.  I don't want those UI issues in LTM.

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-maps/issues/40
