### ISSUE TITLE
Options window

### ISSUE THREAD

**Issue by manbats** [leatrix/leatrix-maps#36]
Option window wont open..

**Comment by leatrix** [comment]
/run leamaps()
or click the minimap button
or go into game keybindings panel and assign a hotkey to toggle the panel
the /ltm slash command will return when Blizzard fix their slash comment system (it causes UI errors at the rmoment)

**Comment by manbats** [comment]
/run leamaps() doesnt work... no mini map button either... nothing in key bindings for leatrix. Thats why i started the issue.
    On Monday, December 5, 2022 at 09:15:14 PM EST, leatrix ***@***.***> wrote:  
 
 


Closed #36 as completed.

**Comment by leatrix** [comment]
It works fine.  Disable other addons and test again.
