### ISSUE TITLE
NO back button

### ISSUE THREAD

**Issue by manbats** [leatrix/leatrix-maps#37]
When yoou select remove boarder it removes the back button for quests so you have to close the map to go back. Also is can you not adjust map size in retail like you can in classic?

**Comment by leatrix** [comment]
You can right-click the quest detail pane to go back to the quest list.  This works with or without the map border.  You really don't need the back button.  Rescaling the map in Dragonflight causes issues so there's no rescale option in LTM for Dragonflight.
