### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Rezy942** [leatrix/leatrix-maps#38]
Hello. Love the addon!!!

Some features I would love to see for dragonflight:

1) Show dungeon/raid locations on world map without having to click zone.
2) Show events that change locations on world map without having to click zone. Events such as feast, ancient waygates, grand hunts, assault, fishing holes, and elemental storms. It is SUCH a pain having to view each map at a time to see where the elemental storms are at now! Or whether the assault is up or not! I hope this is possible to accomplish, im sure a lot of people will use this addon for this feature alone.

Thank you!

Screenshot of world map in dragon isles with addon enabled:
![image](https://user-images.githubusercontent.com/122007087/210740377-41646edb-3ae6-4466-b088-d90400d8a111.png)

**Comment by leatrix** [comment]
Suggestions appreciated.
