### ISSUE TITLE
Leatrix Maps - Unable to remove addon settings

### ISSUE THREAD

**Issue by mtadevic** [leatrix/leatrix-maps#39]
I added Leatrix maps and now, even after uninstalling both Leatrix Plus ,Leatrix Maps and removing the saved variables for both the map will not revert to the defaults and messages about LibDBIcon are still present on the buttons. Any idea how to fully remove this and revert it back to stock?

**Comment by leatrix** [comment]
The Leatrix Plus opton 'Enhance minimap' ('Interface') adds notes to non-standard minimap buttons (i.e. custom buttons that were created without LibDBIcon).  So all you have to do is uncheck 'Enhance minimap' and reload.  Leatrix Plus doesn't modify the minimap at all if 'Enhance minimap' is not enabled.  Leatrix Maps doesn't modify the minimap at all.

**Comment by mtadevic** [comment]
Yep, it was strange, interestingly the thing that was causing me heart burn (stacking the addon buttons) you already had built in! Thanks for the great addons!
