### ISSUE TITLE
Map size

### ISSUE THREAD

**Issue by manbats** [leatrix/leatrix-maps#41]
why is the world map so small now? the  font for the quests is like 8

**Comment by leatrix** [comment]
Do you have 'Scale the map' checked in the configuration panel?  If you do, you can click the cogwheel and set the world map scale.  Or uncheck 'Scale the map' if you don't want the map to be scaled by LTM.

**Comment by manbats** [comment]
Ty. Did not notice that was added
  


Do you have 'Scale the map' checked in the configuration panel? If you do, you can click the cogwheel and set the world map scale. Or uncheck 'Scale the map' if you don't want the map to be scaled by LTM.

**Comment by leatrix** [comment]
It was removed in Dragonflight due to issues with the game code.  However, Blizzard resolved those issues in a recent patch so it was added back again.
