### ISSUE TITLE
Feature Request (optional): increase zoom factor when using maps

### ISSUE THREAD

**Issue by Rezy942** [leatrix/leatrix-maps#42]
For users with lots of handy notes or TomTom coordinates - it would be fantastic to allow to zoom in more.
Additionally, you could let zoom setting to be saved instead of resetting each time you open map.

**Comment by leatrix** [comment]
Exists in Classic but cannot be added to Dragonflight without causing issues.

**Comment by Rezy942** [comment]
Unfortunate. Please consider if this ever changes :)

**Comment by leatrix** [comment]
It's up to Blizzard.  The issues are in their code.
