### ISSUE TITLE
Double Castle Nathria raid entrance icons

### ISSUE THREAD

**Issue by mogol1** [leatrix/leatrix-maps#5]
Enabling the "enhance dungeon icons" option doesn't hide the default raid entrance icon, resulting in both Blizzard's icon and LTM's icon appearing.
![WoWScrnShot_020721_223408](https://user-images.githubusercontent.com/14336484/107172944-a177ee80-6994-11eb-87de-a4d667f3f7a3.jpg)

**Comment by leatrix** [comment]
Many thanks for the report.  It's fixed in the latest alpha (at least 9.0.15.alpha.3).
