### ISSUE TITLE
crash on quest item click

### ISSUE THREAD

**Issue by lukasa1993** [leatrix/leatrix-maps#6]
```
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:519: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua"]:95: in function <...ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua:88>
```
![Screen Shot 2021-02-18 at 11 37 25](https://user-images.githubusercontent.com/1499012/108321491-ae3ee280-71dd-11eb-9641-d66f106fe1d6.png)

**Comment by leatrix** [comment]
This error is harmless but unavoidable.  Reloading your UI should fix it.  You can reduce the chance of it happening by not clicking anything in the objective tracker on the right-side of the screen (especially during combat).

**Comment by lukasa1993** [comment]
i really need it in maw :D and it gets me everytime i am in trouble, any way to silence it ?

**Comment by leatrix** [comment]
You probably saw this error after trying to click a quest item in the objective tracker.  The only way to fix it is to reload your UI and avoid clicking items in the objective tracker especially during combat.  Hiding the error wouldn't fix the problem.  The quest item would remain broken until you reload your UI.

**Comment by lukasa1993** [comment]
> You probably saw this error after trying to click a quest item in the objective tracker. The only way to fix it is to reload your UI and avoid clicking items in the objective tracker especially during combat. Hiding the error wouldn't fix the problem. The quest item would remain broken until you reload your UI.

yes that whats happened but i want to be able to click quest item in objective tracker can addon not get in the way?

**Comment by leatrix** [comment]
There's no way around it sadly, no.
