### ISSUE TITLE
UI windows no longer open in 11.0.7 (The War Within)

### ISSUE THREAD

**Issue by WizardShotTheFood** [leatrix/leatrix-maps#64]
### Issue

The new patch has rendered me unable to open any user interface windows (character, main menu, NPC interaction, etc.) when LTM is enabled -- any attempt to do so, whether by pressing the associated keyboard button or clicking on the icon, just fails silently. The only ones that appear to be unaffected are the quest log and the shop.

### Game version

The War Within

**Comment by leatrix** [comment]
Works fine for me so...

- Disable all addons except LTM.
- Does that fix it?  If so, enable other addons gradually until you find the cause of the problem.
- If that does not fix it, reinstall LTM using CurseForge App.  To do that, right-click the addon in your addon listing and select reinstall.
- Does that fix it?  If not, open Leatrix_Maps\Leatrix_Maps.lua (in your addons folder) with Notepad and tell me the title, version and date information shown at the top of the file.

**Comment by WizardShotTheFood** [comment]
This may be related to #65, since I know I had the option there enabled.

**Comment by WizardShotTheFood** [comment]
Also, it looks like disabling "Unlock map frame" does serve as a workaround, so this is almost certainly the same underlying issue as #65. I'm going to try and close this out as a duplicate for you.
