### ISSUE TITLE
Map Coordinates?

### ISSUE THREAD

**Issue by jediahcorn** [leatrix/leatrix-maps#8]
So... this issue is hardly an issue... but more so an opportunity. I don't see any map coordinate options inside this addon. So. Sadly, I have other addons to do this. However. LTM has a bar at the bottom of the map... RIGHT where every other addon that makes map coordinates happens to place their coordinates. LOL. I'll attach a picture to show what I mean. As you can see, the coordinates overlap with LTM and it's just a mess.

I see two solutions: add a map coordinates option to your addon (I'm sorta surprised not to see it in your addon, feels like such a good fit!) or add an option inside your addon to relocate that bar, or shorten it, or turn it off, or something related.

I sure do hope you read these. This took me a lot of setting up profiles just to write this. LOL. Please excuse my poor doodling. Also, I hope you are not insulted in any way from this message. I really enjoy your addons and I just wanna help improve them!

Please let me know if I can help anyway further?

<3
Jediahcorn

![bigsadmap](https://user-images.githubusercontent.com/31173768/112740423-c7038c00-8f31-11eb-933c-e2322af67415.jpg)

**Comment by leatrix** [comment]
Enter /ltm.
To hide coordinates and the bar, uncheck 'Show coordinates'.  To hide just the bar but keep the coordinates, click the little configuration button next to 'Show coordinates' and uncheck 'Show background'.
